export const EMP =[
    {
        "id":1,
        "name":"sham",
        "salary":"10k",
        "age":"25year",
        "exp":"10y",
    },
    {
        "id":2,
        "name":"Ram",
        "salary":"80k",
        "age":"28year",
        "exp":"5y",
    },
    {
        "id":3,
        "name":"Mohan",
        "salary":"50k",
        "age":"28year",
        "exp":"05y",
    }
] 